In [1]:
import torch
import numpy as np

In [2]:
torch.tensor([[1, 2], [3, 4], [5, 6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [3]:
torch.tensor(np.array([[1, 2], [3, 4], [5, 6]]))

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

In [4]:
torch.zeros([3,2])

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
torch.ones([3,2])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
type(x)

torch.Tensor

In [7]:
x = x.numpy()
type(x)

numpy.ndarray

In [8]:
x = torch.from_numpy(x)
type(x)

torch.Tensor

In [9]:
torch.cuda.is_available()

False

In [10]:
gpu = torch.device('cuda', 0)
cpu = torch.device('cpu')